language: rust
rust:
    - stable
    - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cd xgboost-sys && cargo build --verbose --all
  - cd xgboost-sys && cargo test --verbose --all
